name: Django ci/cd

on:
  push:
    branch: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
     
    env:
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USERS: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
          POSTGRES_DB: ${{ env.PG_NAME }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check changes
        uses: actions/checkout@v2
      - name: list files
        run: ls -la
      - name: python install
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: install requirements
        run: pip install -r requirements.txt
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
       #  key: ${{ secrets.SSH_KEY }}
          script: |
            cd cicd-crud-project 
            git pull 
            systemctll restart gunicorn_crud
            
